replicas: 3

imageTag: 5.4.0

resources:
  requests:
    cpu: 100m
    memory: 4096Mi
kafkaHeapOptions: "-Xmx4G -Xms1G"

configurationOverrides:
  "offsets.topic.replication.factor": 3

topics:
  - name: tweets
    config: "retention.ms=1814400000" # 21 days
    partitions: 4
    replicationFactor: 3
  - name: ubdata
    config: "retention.ms=5443200000,compression.type=snappy" # 63 days
    partitions: 12
    replicationFactor: 2

persistence:
  size: "100Gi"
  storageClass: "pd-ssd"

# keep pods on separate nodes but
# collcated with zookeeper pods
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - kafka
      topologyKey: "kubernetes.io/hostname"
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
     - weight: 50
       podAffinityTerm:
         labelSelector:
           matchExpressions:
           - key: app
             operator: In
             values:
               - zookeeper
         topologyKey: "kubernetes.io/hostname"
