apiVersion: v1
kind: Pod
metadata:
  name: kafkaclient
  namespace: default
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:5.4.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
