image:
  repository: agriuseatstweets/belly
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

schedule: "*/15 * * * *"
completions: 1
parallelism: 1
backoffLimit: 1

resources: {}

queue: {}
# For kafka:
  # queue: "kafka"
  # topic: "tweets"
  # kafkaBrokers: "agrius-kafka:9092"

# set location info
belly: {}
  # location: "gs://foo"
  # size: "90000"
  # minimumSize: "0"
spark:
  partitionSize: "10000"
  driverMemory: "4g"
