image:
  repository: agriuseatstweets/belly
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

schedule: "*/15 * * * *"
completions: 1
parallelism: 1
backoffLimit: 1

resources: {}
queue: {}
belly: {}
