apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-livetweets
spec:
  clusterRef:
    name: kafka
  name: livetweets
  {{- toYaml .Values.kafkaCluster.topics.livetweets | nindent 2 }}

---

apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-tweets
spec:
  clusterRef:
    name: kafka
  name: tweets
  {{- toYaml .Values.kafkaCluster.topics.tweets | nindent 2 }}

---

apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-dig
spec:
  clusterRef:
    name: kafka
  name: dig
  {{- toYaml .Values.kafkaCluster.topics.dig | nindent 2 }}
