belly:
  image:
    repository: agriuseatstweets/bellygo
    tag: 0.0.3
  schedule: "*/10 * * * *"
  completions: 4
  parallelism: 4
  backoffLimit: 5
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
  keySecret: agrius-belly-keys
  env:
    - name: BELLY_TOPIC
      value: "tweets"
    - name: BELLY_LOCATION
      value: "spain-tweets-datalake"
    - name: BELLY_SIZE
      value: "360000"
    - name: BELLY_GROUP
      value: "belly"
    - name: KAFKA_BROKERS
      value: "hydra-kafka:9092"
    - name: KAFKA_POLL_TIMEOUT
      value: "600s"

kafka:
  replicas: 6
  imageTag: 5.4.0
  resources:
    requests:
      cpu: "100m"
      memory: "10Gi"
  kafkaHeapOptions: "-Xmx4G -Xms1G"
  configurationOverrides:
    "offsets.topic.replication.factor": 3
    "group.initial.rebalance.delay.ms": 20000
    "auto.create.topics.enable": false
    "auto.leader.rebalance.enable": false
  topics:
    - name: tweets
      config: "retention.ms=1728000000,compression.type=snappy" # 20 days
      partitions: 12
      replicationFactor: 3
    - name: ubdata
      config: "retention.ms=432000000,compression.type=snappy" # 5 days
      partitions: 12
      replicationFactor: 2
    - name: dig
      config: "retention.ms=432000000" # 5 days
      partitions: 4
      replicationFactor: 2
  persistence:
    size: "1000Gi"
    storageClass: "pd-ssd"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - kafka
        topologyKey: "kubernetes.io/hostname"
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 50
         podAffinityTerm:
           labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
                 - zookeeper
           topologyKey: "kubernetes.io/hostname"
