belly:
  image:
    repository: agriuseatstweets/belly
    tag: 0.0.23
  schedule: "*/30 * * * *"
  completions: 5
  parallelism: 5
  backoffLimit: 2
  resources:
    requests:
      cpu: "1000m"
      memory: "35Gi"
  keySecret: agrius-belly-keys
  queue:
    queue: "kafka"
    topic: "tweets"
    kafkaBrokers: "hydra-kafka:9092"
    kafkaPollInterval: "1920000"
  belly:
    location: "gs://spain-tweets/datalake"
    size: "360000"
  spark:
    driverMemory: "35g"
    partitionSize: "2000"

bellyback:
  image:
    repository: agriuseatstweets/bellyback
    tag: 0.0.4
  schedule: "*/15 * * * *"
  completions: 8
  parallelism: 8
  backoffLimit: 2
  resources:
    requests:
      memory: "3Gi"
  keySecret: agrius-bellyback-keys
  queue:
    queue: "kafka"
    topic: "tweets"
    kafkaBrokers: "hydra-kafka:9092"
    kafkaPollInterval: "1920000"
  belly:
    location: "spain-tweets-backup"
    size: "60"

kafka:
  replicas: 6
  imageTag: 5.4.0
  resources:
    requests:
      cpu: "100m"
      memory: "10Gi"
  kafkaHeapOptions: "-Xmx4G -Xms1G"
  configurationOverrides:
    "offsets.topic.replication.factor": 3
    "group.initial.rebalance.delay.ms": 20000
  topics:
    - name: tweets
      config: "retention.ms=1814400000,compression.type=snappy" # 21 days
      partitions: 12
      replicationFactor: 3
    - name: ubdata
      config: "retention.ms=604800000,compression.type=snappy" # 7 days
      partitions: 12
      replicationFactor: 2
  persistence:
    size: "1000Gi"
    storageClass: "pd-ssd"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - kafka
        topologyKey: "kubernetes.io/hostname"
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 50
         podAffinityTerm:
           labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
                 - zookeeper
           topologyKey: "kubernetes.io/hostname"
