{{- range .Values.bellyLags }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-kafka-agrius-{{ .consumergroup }}-lagging
  labels:
    heritage: Helm
    release: prometheus
  namespace: monitoring
spec:
  groups:
  - name: Agrius belly is beginning to lag
    interval: 6h
    rules:
      - alert: Agrius{{ .alertname }}
        expr: |
          sum(kafka_consumergroup_lag_sum{consumergroup="{{ .consumergroup }}"}) > {{ .limit }}
        for: 180m
        labels:
          severity: warning
        annotations:
          summary: |
            Kafka consumer lag...
          description: |
            Kafka consumer lag...
---
{{- end }}
