{{- range .Values.kafkaTopics }}
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: {{ $.Release.Name }}-topic-{{ .name }}
  namespace: default
spec:
  clusterRef:
    name: kafka
  {{- toYaml . | nindent 2 }}
---
{{- end }}
