apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-tweets
spec:
  clusterRef:
    name: kafka
  name: tweets
  partitions: 8
  replicationFactor: 3
  config:
    "retention.ms": "1728000000"
    "compression.type": "snappy"
