apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-livetweets
spec:
  clusterRef:
    name: kafka
  name: livetweets
  partitions: 1
  replicationFactor: 3
  config:
    "retention.ms": "1728000000"
    "compression.type": "snappy"
