apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-livetweets
spec:
  clusterRef:
    name: kafka
  name: livetweets
  partitions: 1
  replicationFactor: 1
  config:
    "retention.ms": "1728000000"
    "compression.type": "snappy"


---

apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-tweets
spec:
  clusterRef:
    name: kafka
  name: tweets
  partitions: 4
  replicationFactor: 1
  config:
    "retention.ms": "1728000000"
    "compression.type": "snappy"


---

apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: topic-dig
spec:
  clusterRef:
    name: kafka
  name: dig
  partitions: 1
  replicationFactor: 1
  config:
    "retention.ms": "5184000000" # 60 days
    "compression.type": "snappy"
