{
 "title": "K8s / Storage / Volumes / Cluster",
 "description": "Dashboard of Kubernetes / OpenShift volume information at cluster level as exported by Prometheus connected to Kubernetes / OpenShift.",
 "tags": [
  "openshift",
  "k8s",
  "storage"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "60"
   }
  ]
 },
 "panels": [
  { "title": "Current Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  { "title": "Dashboard Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 } },
  {
   "title": "Alert Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table",
     "gridPos": { "h": 14, "w": 7, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "(\n  (\n    (kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"} ) \n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"}[1w], 7 * 24 * 60 * 60) < 0)\n  )\n)"
      }
     ]
    },
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  (\n    ((kubelet_volume_stats_used_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"} ) * 0) + 1\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Predicted Available Space History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 15 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "User Namespace Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "(\n  (\n    (\n      (kubelet_volume_stats_used_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\"})\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)"
      }
     ]
    },
    {
     "title": "User Namespace Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  (\n    (\n      (\n        (kubelet_volume_stats_used_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\"})\n      )\n      * 0 + 1\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "User Namespace Volumes Full in Week Based on Daily Use Rate - Predicted Available Space History",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 28 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "1 Week Predicted Available Space"
      }
     ],
     "targets": [
      {
       "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold Stats - Current",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "(kube_persistentvolumeclaim_info) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes)) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes )) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) >= ($pvc_percent_used_warning_threshold / 100)"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold - History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "# of Alerts" }
     ],
     "targets": [
      {
       "expr": "(\n  ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) * 0 +1)\n  and\n  (\n    (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes ))\n  ) >= ($pvc_percent_used_warning_threshold / 100)\n)"
      }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "PVC Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info"
    },
    {
     "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info ) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes )) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info ) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes )))"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes)"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes )"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes ))"
    }
   ]
  },
  { "title": "Use", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes ))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Running PVCs % Used",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes )) * 100",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "Use Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Hourly Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1h])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Weekly Volume Use Rate",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes [1w])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  }
 ]
}