image:
  repository: agriuseatstweets/bellyback
  tag: latest
  pullPolicy: Always

fullnameOverride: ""

schedule: "*/15 * * * *"
completions: 1
parallelism: 1
backoffLimit: 1

resources: {}
queue: {}
belly: {}
